name: Publish @timrefsix/in-app-purchase
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          # Defaults to the user or organization that owns the workflow file
          scope: '@timrefsix'
      - name:  'Automated Github Action Version Bump'
        uses:  'rimonhanna/gh-action-bump-version@master'
      - run: npm whoami
      - run: npm whoami
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
